/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// DetailedProjectApiResult
    /// </summary>
    [DataContract(Name = "DetailedProjectApiResult")]
    public partial class DetailedProjectApiResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DetailedProjectApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DetailedProjectApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DetailedProjectApiResult" /> class.
        /// </summary>
        /// <param name="attributesScheme">Collection of the project attributes.</param>
        /// <param name="workflow">ID of the workflow used in project (required).</param>
        /// <param name="id">Unique ID of the project (required).</param>
        /// <param name="description">Description of the project.</param>
        /// <param name="name">Name of the project (required).</param>
        /// <param name="isFavorite">Indicates if the project is marked as favorite (required).</param>
        /// <param name="isDeleted">Indicates if the project is deleted (required).</param>
        /// <param name="globalId">Global ID of the project (required).</param>
        /// <param name="workflowId">ID of the workflow used in project (required).</param>
        public DetailedProjectApiResult(List<CustomAttributeApiResult> attributesScheme = default, WorkflowApiResult workflow = default, Guid id = default, string description = default, string name = default, bool isFavorite = default, bool isDeleted = default, long globalId = default, Guid workflowId = default)
        {
            // to ensure "workflow" is required (not null)
            if (workflow == null)
            {
                throw new ArgumentNullException("workflow is a required property for DetailedProjectApiResult and cannot be null");
            }
            this.Workflow = workflow;
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for DetailedProjectApiResult and cannot be null");
            }
            this.Name = name;
            this.IsFavorite = isFavorite;
            this.IsDeleted = isDeleted;
            this.GlobalId = globalId;
            this.WorkflowId = workflowId;
            this.AttributesScheme = attributesScheme;
            this.Description = description;
        }

        /// <summary>
        /// Collection of the project attributes
        /// </summary>
        /// <value>Collection of the project attributes</value>
        [DataMember(Name = "attributesScheme", EmitDefaultValue = true)]
        public List<CustomAttributeApiResult> AttributesScheme { get; set; }

        /// <summary>
        /// ID of the workflow used in project
        /// </summary>
        /// <value>ID of the workflow used in project</value>
        [DataMember(Name = "workflow", IsRequired = true, EmitDefaultValue = true)]
        public WorkflowApiResult Workflow { get; set; }

        /// <summary>
        /// Unique ID of the project
        /// </summary>
        /// <value>Unique ID of the project</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Description of the project
        /// </summary>
        /// <value>Description of the project</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Name of the project
        /// </summary>
        /// <value>Name of the project</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Indicates if the project is marked as favorite
        /// </summary>
        /// <value>Indicates if the project is marked as favorite</value>
        [DataMember(Name = "isFavorite", IsRequired = true, EmitDefaultValue = true)]
        public bool IsFavorite { get; set; }

        /// <summary>
        /// Indicates if the project is deleted
        /// </summary>
        /// <value>Indicates if the project is deleted</value>
        [DataMember(Name = "isDeleted", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Global ID of the project
        /// </summary>
        /// <value>Global ID of the project</value>
        [DataMember(Name = "globalId", IsRequired = true, EmitDefaultValue = true)]
        public long GlobalId { get; set; }

        /// <summary>
        /// ID of the workflow used in project
        /// </summary>
        /// <value>ID of the workflow used in project</value>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public Guid WorkflowId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DetailedProjectApiResult {\n");
            sb.Append("  AttributesScheme: ").Append(AttributesScheme).Append("\n");
            sb.Append("  Workflow: ").Append(Workflow).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsFavorite: ").Append(IsFavorite).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  GlobalId: ").Append(GlobalId).Append("\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
