/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// GlobalCustomAttributePostApiModel
    /// </summary>
    [DataContract(Name = "GlobalCustomAttributePostApiModel")]
    public partial class GlobalCustomAttributePostApiModel : IValidatableObject
    {

        /// <summary>
        /// Type of attribute
        /// </summary>
        /// <value>Type of attribute</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public CustomAttributeType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalCustomAttributePostApiModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GlobalCustomAttributePostApiModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalCustomAttributePostApiModel" /> class.
        /// </summary>
        /// <param name="name">Name of attribute (required).</param>
        /// <param name="isEnabled">Indicates whether the attribute is available.</param>
        /// <param name="isRequired">Indicates whether the attribute value is mandatory to specify.</param>
        /// <param name="options">Collection of attribute options   Available for attributes of type &#x60;options&#x60; and &#x60;multiple options&#x60; only.</param>
        /// <param name="type">Type of attribute (required).</param>
        public GlobalCustomAttributePostApiModel(string name = default, bool? isEnabled = default, bool? isRequired = default, List<CustomAttributeOptionPostApiModel> options = default, CustomAttributeType type = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for GlobalCustomAttributePostApiModel and cannot be null");
            }
            this.Name = name;
            this.Type = type;
            this.IsEnabled = isEnabled;
            this.IsRequired = isRequired;
            this.Options = options;
        }

        /// <summary>
        /// Name of attribute
        /// </summary>
        /// <value>Name of attribute</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Indicates whether the attribute is available
        /// </summary>
        /// <value>Indicates whether the attribute is available</value>
        [DataMember(Name = "isEnabled", EmitDefaultValue = true)]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// Indicates whether the attribute value is mandatory to specify
        /// </summary>
        /// <value>Indicates whether the attribute value is mandatory to specify</value>
        [DataMember(Name = "isRequired", EmitDefaultValue = true)]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// Collection of attribute options   Available for attributes of type &#x60;options&#x60; and &#x60;multiple options&#x60; only
        /// </summary>
        /// <value>Collection of attribute options   Available for attributes of type &#x60;options&#x60; and &#x60;multiple options&#x60; only</value>
        [DataMember(Name = "options", EmitDefaultValue = true)]
        public List<CustomAttributeOptionPostApiModel> Options { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GlobalCustomAttributePostApiModel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsEnabled: ").Append(IsEnabled).Append("\n");
            sb.Append("  IsRequired: ").Append(IsRequired).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 0.", new [] { "Name" });
            }

            yield break;
        }
    }

}
