/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// Defines LayerSource
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LayerSource
    {
        /// <summary>
        /// Enum Manual for value: Manual
        /// </summary>
        [EnumMember(Value = "Manual")]
        Manual = 1,

        /// <summary>
        /// Enum Report for value: Report
        /// </summary>
        [EnumMember(Value = "Report")]
        Report = 2,

        /// <summary>
        /// Enum Run for value: Run
        /// </summary>
        [EnumMember(Value = "Run")]
        Run = 3,

        /// <summary>
        /// Enum Rule for value: Rule
        /// </summary>
        [EnumMember(Value = "Rule")]
        Rule = 4
    }

}
