/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// Defines WorkItemEntityTypeApiModel
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WorkItemEntityTypeApiModel
    {
        /// <summary>
        /// Enum TestCases for value: TestCases
        /// </summary>
        [EnumMember(Value = "TestCases")]
        TestCases = 1,

        /// <summary>
        /// Enum CheckLists for value: CheckLists
        /// </summary>
        [EnumMember(Value = "CheckLists")]
        CheckLists = 2,

        /// <summary>
        /// Enum SharedSteps for value: SharedSteps
        /// </summary>
        [EnumMember(Value = "SharedSteps")]
        SharedSteps = 3
    }

}
