/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// WorkflowStatusApiResult
    /// </summary>
    [DataContract(Name = "WorkflowStatusApiResult")]
    public partial class WorkflowStatusApiResult : IValidatableObject
    {

        /// <summary>
        /// Collection of possible status types
        /// </summary>
        /// <value>Collection of possible status types</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TestStatusApiType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStatusApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowStatusApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStatusApiResult" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="code">code (required).</param>
        /// <param name="type">Collection of possible status types (required).</param>
        public WorkflowStatusApiResult(Guid id = default, string code = default, TestStatusApiType type = default)
        {
            this.Id = id;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for WorkflowStatusApiResult and cannot be null");
            }
            this.Code = code;
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowStatusApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
