/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: adapters
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TestIT.AdaptersApi.Client.FileParameter;
using OpenAPIDateConverter = TestIT.AdaptersApi.Client.OpenAPIDateConverter;

namespace TestIT.AdaptersApi.Model
{
    /// <summary>
    /// WorkItemShortApiResult
    /// </summary>
    [DataContract(Name = "WorkItemShortApiResult")]
    public partial class WorkItemShortApiResult : IValidatableObject
    {

        /// <summary>
        /// The current state of Work Item
        /// </summary>
        /// <value>The current state of Work Item</value>
        [DataMember(Name = "state", IsRequired = true, EmitDefaultValue = true)]
        public WorkItemStates State { get; set; }

        /// <summary>
        /// Work Item priority level
        /// </summary>
        /// <value>Work Item priority level</value>
        [DataMember(Name = "priority", IsRequired = true, EmitDefaultValue = true)]
        public WorkItemPriorityModel Priority { get; set; }

        /// <summary>
        /// Work Item priority level
        /// </summary>
        /// <value>Work Item priority level</value>
        [DataMember(Name = "sourceType", IsRequired = true, EmitDefaultValue = true)]
        public WorkItemSourceTypeModel SourceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemShortApiResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkItemShortApiResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkItemShortApiResult" /> class.
        /// </summary>
        /// <param name="id">Work Item internal unique identifier (required).</param>
        /// <param name="name">Work Item name (required).</param>
        /// <param name="entityTypeName">Work Item type. Possible values: CheckLists, SharedSteps, TestCases (required).</param>
        /// <param name="projectId">Project unique identifier (required).</param>
        /// <param name="sectionId">Identifier of Section where Work Item is located (required).</param>
        /// <param name="sectionName">Section name of Work Item (required).</param>
        /// <param name="isAutomated">Boolean flag determining whether Work Item is automated (required).</param>
        /// <param name="globalId">Work Item global identifier (required).</param>
        /// <param name="duration">Work Item duration (required).</param>
        /// <param name="attributes">Work Item attributes.</param>
        /// <param name="state">The current state of Work Item (required).</param>
        /// <param name="priority">Work Item priority level (required).</param>
        /// <param name="sourceType">Work Item priority level (required).</param>
        /// <param name="isDeleted">Flag determining whether Work Item is deleted (required).</param>
        /// <param name="tagNames">Array of tag names of Work Item.</param>
        /// <param name="iterations">Set of iterations related to Work Item (required).</param>
        /// <param name="links">Set of links related to Work Item (required).</param>
        public WorkItemShortApiResult(Guid id = default, string name = default, string entityTypeName = default, Guid projectId = default, Guid sectionId = default, string sectionName = default, bool isAutomated = default, long globalId = default, long duration = default, Dictionary<string, Object> attributes = default, WorkItemStates state = default, WorkItemPriorityModel priority = default, WorkItemSourceTypeModel sourceType = default, bool isDeleted = default, List<string> tagNames = default, List<IterationApiResult> iterations = default, List<LinkShortApiResult> links = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for WorkItemShortApiResult and cannot be null");
            }
            this.Name = name;
            // to ensure "entityTypeName" is required (not null)
            if (entityTypeName == null)
            {
                throw new ArgumentNullException("entityTypeName is a required property for WorkItemShortApiResult and cannot be null");
            }
            this.EntityTypeName = entityTypeName;
            this.ProjectId = projectId;
            this.SectionId = sectionId;
            // to ensure "sectionName" is required (not null)
            if (sectionName == null)
            {
                throw new ArgumentNullException("sectionName is a required property for WorkItemShortApiResult and cannot be null");
            }
            this.SectionName = sectionName;
            this.IsAutomated = isAutomated;
            this.GlobalId = globalId;
            this.Duration = duration;
            this.State = state;
            this.Priority = priority;
            this.SourceType = sourceType;
            this.IsDeleted = isDeleted;
            // to ensure "iterations" is required (not null)
            if (iterations == null)
            {
                throw new ArgumentNullException("iterations is a required property for WorkItemShortApiResult and cannot be null");
            }
            this.Iterations = iterations;
            // to ensure "links" is required (not null)
            if (links == null)
            {
                throw new ArgumentNullException("links is a required property for WorkItemShortApiResult and cannot be null");
            }
            this.Links = links;
            this.Attributes = attributes;
            this.TagNames = tagNames;
        }

        /// <summary>
        /// Work Item internal unique identifier
        /// </summary>
        /// <value>Work Item internal unique identifier</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Work Item name
        /// </summary>
        /// <value>Work Item name</value>
        /*
        <example>Performance test</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Work Item type. Possible values: CheckLists, SharedSteps, TestCases
        /// </summary>
        /// <value>Work Item type. Possible values: CheckLists, SharedSteps, TestCases</value>
        /*
        <example>TestCases</example>
        */
        [DataMember(Name = "entityTypeName", IsRequired = true, EmitDefaultValue = true)]
        public string EntityTypeName { get; set; }

        /// <summary>
        /// Project unique identifier
        /// </summary>
        /// <value>Project unique identifier</value>
        [DataMember(Name = "projectId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ProjectId { get; set; }

        /// <summary>
        /// Identifier of Section where Work Item is located
        /// </summary>
        /// <value>Identifier of Section where Work Item is located</value>
        [DataMember(Name = "sectionId", IsRequired = true, EmitDefaultValue = true)]
        public Guid SectionId { get; set; }

        /// <summary>
        /// Section name of Work Item
        /// </summary>
        /// <value>Section name of Work Item</value>
        /*
        <example>Performance tests section</example>
        */
        [DataMember(Name = "sectionName", IsRequired = true, EmitDefaultValue = true)]
        public string SectionName { get; set; }

        /// <summary>
        /// Boolean flag determining whether Work Item is automated
        /// </summary>
        /// <value>Boolean flag determining whether Work Item is automated</value>
        [DataMember(Name = "isAutomated", IsRequired = true, EmitDefaultValue = true)]
        public bool IsAutomated { get; set; }

        /// <summary>
        /// Work Item global identifier
        /// </summary>
        /// <value>Work Item global identifier</value>
        [DataMember(Name = "globalId", IsRequired = true, EmitDefaultValue = true)]
        public long GlobalId { get; set; }

        /// <summary>
        /// Work Item duration
        /// </summary>
        /// <value>Work Item duration</value>
        [DataMember(Name = "duration", IsRequired = true, EmitDefaultValue = true)]
        public long Duration { get; set; }

        /// <summary>
        /// Work Item attributes
        /// </summary>
        /// <value>Work Item attributes</value>
        [DataMember(Name = "attributes", EmitDefaultValue = true)]
        public Dictionary<string, Object> Attributes { get; set; }

        /// <summary>
        /// Flag determining whether Work Item is deleted
        /// </summary>
        /// <value>Flag determining whether Work Item is deleted</value>
        [DataMember(Name = "isDeleted", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Array of tag names of Work Item
        /// </summary>
        /// <value>Array of tag names of Work Item</value>
        [DataMember(Name = "tagNames", EmitDefaultValue = true)]
        public List<string> TagNames { get; set; }

        /// <summary>
        /// Set of iterations related to Work Item
        /// </summary>
        /// <value>Set of iterations related to Work Item</value>
        [DataMember(Name = "iterations", IsRequired = true, EmitDefaultValue = true)]
        public List<IterationApiResult> Iterations { get; set; }

        /// <summary>
        /// Set of links related to Work Item
        /// </summary>
        /// <value>Set of links related to Work Item</value>
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public List<LinkShortApiResult> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkItemShortApiResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  EntityTypeName: ").Append(EntityTypeName).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  SectionId: ").Append(SectionId).Append("\n");
            sb.Append("  SectionName: ").Append(SectionName).Append("\n");
            sb.Append("  IsAutomated: ").Append(IsAutomated).Append("\n");
            sb.Append("  GlobalId: ").Append(GlobalId).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  SourceType: ").Append(SourceType).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("  TagNames: ").Append(TagNames).Append("\n");
            sb.Append("  Iterations: ").Append(Iterations).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
