name: Check Importer

on:
  pull_request:
    paths:
        - "Importer/**"

env:
  IMPORTER_DIR: ./Importer

jobs:

  importer_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: win-x64
            artifact_name: Importer.exe
            asset_name: Importer-win-x64-TEST.exe
          - os: linux-x64
            artifact_name: Importer
            asset_name: Importer-linux-x64-TEST
          # disabled  
          # - os: osx-x64
          #   artifact_name: Importer
          #   asset_name: Importer-osx-x64-TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8

      - name: Restore dependencies
        run: dotnet restore ${{ env.IMPORTER_DIR }}

      - name: Publish project
        run: |
          dotnet publish \
          -r ${{ matrix.os }} \
          --configuration Release \
          --self-contained true \
          --output ./publish \
          --no-restore ${{ env.IMPORTER_DIR }} 

  