name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
        description: "Path to the test project"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project_path }}

      - name: Build project
        run: dotnet test ${{ inputs.project_path }} --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/*/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'  

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: ${{ inputs.project_path }}
          hide_and_recreate: true
          path: code-coverage-results.md
    
      # - name: Write to Job Summary
      #   run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY    
      - name: Create code coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:coverage/*/coverage.cobertura.xml -targetdir:CodeCoverage -reporttypes:MarkdownSummaryGithub

      - name: Write to Job Summary
        run: cat CodeCoverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
